export const projects = [
  {
    id: 0,
    title: "Image Uploader",
    description: "A tool for uploading and copying images to clipboard.",
    image: "/image-uploader.png",
    status: "Finished",
    link: "https://so8os-image-uploader.vercel.app/",
    github: "https://github.com/So8oS/image-uploader-next",
  },
  {
    id: 1,
    title: "Quote Generator",
    description: "Generates random quotes on button click.",
    image: "/quote-generator.png",
    status: "Finished",
    link: "https://ahmadothman-quotegenerator.netlify.app/",
    github: "https://github.com/So8oS/quotes",
  },
  {
    id: 2,
    title: "Meooww",
    description:
      " Just a cute page with cat pics that I made to practice tailwind css.",
    image: "/meow.png",
    status: "Finished",
    link: "https://meooww.netlify.app/",
    github: "https://github.com/So8oS/tailwind_practice_meoowww",
  },
  {
    id: 3,
    title: "My Unsplash",
    description:
      "This app allows you to store and access your favorite Unsplash pictures in one place.",
    image: "/myunsplash.png",
    status: "Finished",
    link: "https://so8os-unsplash.vercel.app/",
    github: "https://github.com/So8oS/so8os-unsplash",
  },
  {
    id: 4,
    title: "Cat wiki",
    description: "A website to browse cat breeds and know more about them.",
    image: "/catwiki.png",
    status: "Finished",
    link: "https://catwiki.ahmadothman.com/",
    github: "https://github.com/So8oS/catwiki",
  },
  {
    id: 5,
    title: "SMDB",
    description: "A movie database where you can browse movies.",
    image: "/smdb.png",
    status: "Finished",
    link: "https://smdb.ahmadothman.com/",
    github: "https://github.com/So8oS/smdb",
  },
  {
    id: 6,
    title: "Le Khalil Le Cookies",
    description:
      "A website for my friends cookie bussines that he sadly no longer runs(pixel art themed).",
    image: "/lekhalilecookies.png",
    status: "Finished",
    link: "https://lekhalillecookies.ahmadothman.com/",
    github: "https://github.com/So8oS/le_khalil_le_cookies_v3",
  },
  {
    id: 7,
    title: "Ancient Gamer",
    description:
      "A website for my social media/Youtube page Ancient Gamer which has the content along with the games.",
    image: "/ancientgamer.png",
    status: "Finished",
    link: "https://www.ancientgamer.net/",
    github: "https://github.com/So8oS/ancient_gamer",
  },
  {
    id: 8,
    title: "Foodie",
    description:
      "A social media food review app where reviews are only videos. a place to go to when you dont know what to eat.",
    image: "/foodie.png",
    status: "Ongoing",
    link: "",
    github: "https://github.com/So8oS/foodie",
  },
  {
    id: 9,
    title: "CVSCO",
    description:
      "A simpler VSCO knockoff (cheaper vsco). Photo sharing platform.",
    image: "/cvscopic.png",
    status: "Finished",
    link: "https://cvsco-so8os.vercel.app/",
    github: "",
  },
];

export const techStack = [
  { name: "React JS", src: "/Icons/react.svg" },
  { name: "Next JS", src: "/Icons/next.svg" },
  { name: "CSS", src: "/Icons/css.svg" },
  { name: "Tailwind CSS", src: "/Icons/tailwind.svg" },
  { name: "Javascript", src: "/Icons/javascript.svg" },
  { name: "Typescript", src: "/Icons/typescript.svg" },
  { name: "Prisma", src: "/Icons/prisma.svg" },
  { name: "Vercel", src: "/Icons/vercel.svg" },
  { name: "C#", src: "/Icons/csharp.svg" },
];
